### ISSUE TITLE
Design Layout Overhaul (Dashboard)

### ISSUE THREAD

**Issue by fesimon** [fesimon/chartjs-data-visualisation#25]
## TODO
- [x] Seperate Site-Content from Sidebar (for scalability)
- [x] Build togglable, mobile-friendly Sidebar
  - [x] Desktop: (Small & Large), Mobile: (Show/Hide)
- [x] Modularize Components (BS-Cards?)
- [x] Simplify Charts (Display Axes only if necessary)
### Reference
- [Dashboard Design](https://blackrockdigital.github.io/startbootstrap-sb-admin-2/index.html)
